const KEY="yeie_v01";let state=JSON.parse(localStorage.getItem(KEY)||'{"entries":[],"ideas":[]}'),editingEntryId=null;const $=id=>document.getElementById(id),save=()=>localStorage.setItem(KEY,JSON.stringify(state)),LOCK=24*60*60*1000;const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const date=s=>new Date(s).toLocaleString([],{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'});const locked=e=>Date.now()-new Date(e.createdAt).getTime()>=LOCK;
function view(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===id))}
function render(){let b=$('recentEntries');$('entryCount').textContent=state.entries.length;if(!state.entries.length){b.className='entries empty-state';b.innerHTML='<p>Nothing here yet.</p><p>Write without worrying about what to call it.</p>'}else{b.className='entries';b.innerHTML=[...state.entries].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(e=>`<article class="card"><button data-id="${e.id}"><div class="card-title">${date(e.createdAt)}</div><div class="card-date">${locked(e)?'Locked':'Open for 24 hours'}</div><div class="card-preview">${esc(e.body)}</div></button></article>`).join('');b.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openEntry(x.dataset.id))}}
function newEntry(){editingEntryId=null;$('bodyInput').value='';$('entryMeta').textContent=date(new Date().toISOString());$('entryStatus').textContent='Private · starts now';$('lockMessage').textContent='Locks after 24 hours.';$('saveEntryBtn').style.display='inline-block';view('entryView');setTimeout(()=>$('bodyInput').focus(),30)}
function openEntry(id){let e=state.entries.find(x=>x.id===id);if(!e)return;editingEntryId=id;$('bodyInput').value=e.body;$('entryMeta').textContent=date(e.createdAt);$('entryStatus').textContent=locked(e)?'Locked':'Private · open';$('lockMessage').textContent=locked(e)?'Locked. Write the next entry.':'You can continue this entry until it locks.';$('saveEntryBtn').style.display=locked(e)?'none':'inline-block';view('entryView')}
$('newEntryBtn').onclick=newEntry;$('backBtn').onclick=()=>{render();view('homeView')};$('entryForm').onsubmit=e=>{e.preventDefault();let body=$('bodyInput').value.trim();if(!body)return;if(editingEntryId){let x=state.entries.find(x=>x.id===editingEntryId);if(!x||locked(x))return;x.body=body;x.updatedAt=new Date().toISOString()}else state.entries.push({id:crypto.randomUUID(),body,createdAt:new Date().toISOString()});save();render();view('homeView')};
const paths={sound:['A SOUND','What sound keeps pulling your attention? What does it remind you of?'],image:['A SCENE','Where are you? Who is there? What is nobody saying?'],words:['A LINE','Write one sentence you can’t stop thinking about.'],question:['A QUESTION','What do you believe because someone else taught you to believe it?'],story:['A MOMENT','Describe one ordinary moment as if it belongs in a film.']};const stuck=[['WHERE DID THIS COME FROM?','Pick the idea you keep returning to. Where did you first learn it?'],['WHO TAUGHT YOU THAT?','Think of something you believe about success, love, family, or yourself. Who taught you?'],['WHAT ARE YOU AVOIDING?','What thought keeps getting pushed aside because it might change something?'],['WHAT IF YOU’RE WRONG?','Choose one belief you feel certain about. What would change if it wasn’t true?'],['WHAT WOULD YOU MAKE IF NOBODY SAW IT?','No audience. No algorithm. No explanation. What would you create?']];
function wander(title,body,trail){let b=$('wanderResult');b.classList.remove('hidden');b.innerHTML=`<div class="result-kicker">${esc(trail)}</div><div class="result-title">${esc(title)}</div><div class="result-body">${esc(body)}</div><div class="result-actions"><button class="ghost" id="follow">Follow this</button><button class="ghost" id="again">Another path</button></div>`;$('follow').onclick=()=>{view('ideaView');$('ideaInput').value=title;$('ideaBodyInput').value='';$('ideaTrail').textContent=trail};$('again').onclick=()=>b.classList.add('hidden')}
document.querySelectorAll('.path-card').forEach(x=>x.onclick=()=>{let q=paths[x.dataset.path];wander(q[0],q[1],x.querySelector('b').textContent)});$('lostBtn').onclick=()=>{let q=stuck[Math.floor(Math.random()*stuck.length)];wander(q[0],q[1],'LOST? · LET’S START SOMEWHERE')};
$('ideaForm').onsubmit=e=>{e.preventDefault();let t=$('ideaInput').value.trim(),b=$('ideaBodyInput').value.trim();if(!t&&!b)return;state.ideas.push({id:crypto.randomUUID(),title:t||'Untitled thought',body:b,createdAt:new Date().toISOString()});save();view('wanderView')};$('ideaBackBtn').onclick=()=>view('wanderView');document.querySelectorAll('.nav-btn').forEach(x=>x.onclick=()=>view(x.dataset.view));$('lockBtn').onclick=()=>$('privacyModal').classList.remove('hidden');$('closeModal').onclick=()=>$('privacyModal').classList.add('hidden');$('privacyModal').onclick=e=>{if(e.target.id==='privacyModal')$('privacyModal').classList.add('hidden')};render();
