const KEY="yeie_v01",DRAFT_KEY="yeie_journal_draft_v022",LOCK_HOURS=24;
const $=id=>document.getElementById(id); let state,editingEntryId=null,draftTimer=null,countdownTimer=null;
try{state=JSON.parse(localStorage.getItem(KEY)||'{"entries":[],"ideas":[]}');state.entries??=[];state.ideas??=[]}catch{state={entries:[],ideas:[]}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),nowISO=()=>new Date().toISOString();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const formatDate=iso=>new Date(iso).toLocaleString([],{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"});
const locked=e=>Date.now()-new Date(e.createdAt).getTime()>=LOCK_HOURS*3600000;
function view(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===id));scrollTo(0,0)}
function renderJournal(){const b=$("recentEntries");$("entryCount").textContent=state.entries.length;if(!state.entries.length){b.className="entries empty-state";b.innerHTML="<p>Nothing here yet.</p><p>Write without worrying about what to call it.</p>";return}b.className="entries";b.innerHTML=[...state.entries].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(e=>`<article class="card"><button type="button" data-open="${e.id}"><div class="card-title">${formatDate(e.createdAt)}</div><div class="card-date">${locked(e)?"Locked":"Open for 24 hours"}</div><div class="card-preview">${esc(e.body)}</div></button></article>`).join("");b.querySelectorAll("[data-open]").forEach(x=>x.onclick=()=>openEntry(x.dataset.open))}
function renderFound(){const b=$("ideasList");if(!state.ideas.length){b.className="entries empty-state";b.innerHTML="<p>You haven't found anything yet.</p><p>Go wander. Follow something.</p>";return}b.className="entries";b.innerHTML=[...state.ideas].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(i=>`<article class="card"><div class="card-title">${esc(i.title||"Untitled thought")}</div><div class="card-date">${formatDate(i.createdAt)}</div><div class="card-preview">${esc(i.body||"")}</div></article>`).join("")}
function draft(){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||"null")}catch{return null}}
function autosave(){const body=$("bodyInput").value;if(!body.trim()){localStorage.removeItem(DRAFT_KEY);return}const d=draft();const x={body,savedAt:nowISO(),editingEntryId:editingEntryId||null,createdAt:d?.createdAt||nowISO()};localStorage.setItem(DRAFT_KEY,JSON.stringify(x));$("lockMessage").textContent=`Draft autosaved · ${new Date(x.savedAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`}
function clearDraft(){localStorage.removeItem(DRAFT_KEY)}
function countdown(){if(!editingEntryId)return;const e=state.entries.find(x=>x.id===editingEntryId);if(!e)return;if(locked(e)){$("entryStatus").textContent="Locked";$("lockMessage").textContent="Locked. Don't rewrite it. Write the next entry.";$("saveEntryBtn").style.display="none";$("bodyInput").disabled=true;clearInterval(countdownTimer);return}const s=Math.max(0,Math.floor((new Date(e.createdAt).getTime()+LOCK_HOURS*3600000-Date.now())/1000));$("lockMessage").textContent=`Locks in ${Math.floor(s/3600)}h ${String(Math.floor(s%3600/60)).padStart(2,"0")}m ${String(s%60).padStart(2,"0")}s`}
function newEntry(){editingEntryId=null;const d=draft();$("bodyInput").value=d?.body||"";$("entryMeta").textContent=d?.body?"Unfinished draft recovered":formatDate(nowISO());$("entryStatus").textContent=d?.body?"Draft recovered":"Private · starts now";$("lockMessage").textContent=d?.body?"Draft recovered. Autosave is on.":"Draft autosave is on.";$("saveEntryBtn").style.display="inline-block";$("bodyInput").disabled=false;view("entryView");clearInterval(draftTimer);draftTimer=setInterval(autosave,1500);$("bodyInput").oninput=autosave;setTimeout(()=>$("bodyInput").focus(),50)}
function openEntry(id){const e=state.entries.find(x=>x.id===id);if(!e)return;editingEntryId=id;$("bodyInput").value=e.body||"";$("entryMeta").textContent=formatDate(e.createdAt);$("entryStatus").textContent=locked(e)?"Locked":"Private · open";$("bodyInput").disabled=locked(e);$("saveEntryBtn").style.display=locked(e)?"none":"inline-block";view("entryView");clearInterval(countdownTimer);if(!locked(e)){countdownTimer=setInterval(countdown,1000);countdown() }else $("lockMessage").textContent="Locked. Don't rewrite it. Write the next entry."}
$("newEntryBtn").onclick=newEntry;
$("backBtn").onclick=()=>{autosave();clearInterval(draftTimer);clearInterval(countdownTimer);renderJournal();view("homeView")};
$("entryForm").onsubmit=e=>{e.preventDefault();const body=$("bodyInput").value.trim();if(!body)return;if(editingEntryId){const x=state.entries.find(y=>y.id===editingEntryId);if(!x||locked(x))return;x.body=body;x.updatedAt=nowISO()}else state.entries.push({id:crypto.randomUUID(),body,createdAt:nowISO()});save();clearDraft();clearInterval(draftTimer);clearInterval(countdownTimer);renderJournal();view("homeView")};

const wander={sound:[["A SOUND","What sound keeps pulling your attention? What does it remind you of?"],["A FEELING","If this feeling had a tempo, a room, and a sound, what would they be?"]],image:[["AN IMAGE","What is the first thing you notice? What happened right before this frame?"],["A SCENE","Where are you? Who is there? What is nobody saying?"]],words:[["A LINE","Write one sentence you can't stop thinking about."],["A LYRIC","Write four lines without trying to make them good."]],question:[["A QUESTION","What are you curious about but afraid might have no clean answer?"],["AN ASSUMPTION","What do you believe because someone else taught you to believe it?"]],story:[["A PERSON","Who have you been thinking about lately? What don't you understand about them?"],["A MEMORY","Pick a memory. What detail do you remember that nobody else could have noticed?"]]};
const stuck=[["WHERE DID THIS COME FROM?","Pick the idea you keep returning to. Where did you first learn it?"],["WHO TAUGHT YOU THAT?","Think of something you believe about success, love, family, or yourself. Who taught you?"],["WHAT ARE YOU AVOIDING?","What thought keeps getting pushed to the side because it might change something?"]];
function result(t,b,tr){const x=$("wanderResult");x.classList.remove("hidden");x.innerHTML=`<div class="result-kicker">${esc(tr)}</div><div class="result-title">${esc(t)}</div><div class="result-body">${esc(b)}</div><div class="result-actions"><button class="ghost" id="followBtn">Follow this</button><button class="ghost" id="anotherBtn">Another path</button></div>`;$("followBtn").onclick=()=>{ $("ideaInput").value=t;$("ideaBodyInput").value="";$("ideaTrail").textContent=tr;$("ideaForm").dataset.seed=b;view("ideaView")};$("anotherBtn").onclick=()=>x.classList.add("hidden")}
document.querySelectorAll(".path-card").forEach(b=>b.onclick=()=>{const x=wander[b.dataset.path][Math.floor(Math.random()*wander[b.dataset.path].length)];result(x[0],x[1],b.querySelector("b").textContent)});
$("lostBtn").onclick=()=>{const x=stuck[Math.floor(Math.random()*stuck.length)];result(x[0],x[1],"LOST? · LET'S START SOMEWHERE")};
$("ideaForm").onsubmit=e=>{e.preventDefault();const t=$("ideaInput").value.trim(),b=$("ideaBodyInput").value.trim();if(!t&&!b)return;state.ideas.push({id:crypto.randomUUID(),title:t||"Untitled thought",body:b||e.currentTarget.dataset.seed||"",createdAt:nowISO()});e.currentTarget.dataset.seed="";save();renderFound();view("ideasView")};
$("ideaBackBtn").onclick=()=>view("wanderView");
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>{if(b.dataset.view==="homeView")renderJournal();if(b.dataset.view==="ideasView")renderFound();view(b.dataset.view)});
$("lockBtn").onclick=()=>$("privacyModal").classList.remove("hidden");$("closeModal").onclick=()=>$("privacyModal").classList.add("hidden");$("privacyModal").onclick=e=>{if(e.target.id==="privacyModal")$("privacyModal").classList.add("hidden")};
renderJournal();renderFound();